# ansible-galaxy role install -r requirements.yml && ansible-galaxy collection install -r requirements.yml
collections:
  - name: elreydetoda.virtualization
  - name: amazon.aws
    version: 2.0.0
  - name: community.general
    version: 8.1.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.docker
    version: 3.10.4
roles:
  - name: elreydetoda.gh_dl
  - name: elreydetoda.nessus
